[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "MVAPICH"
authors = [{name = "NOWLAB", email = "mvapich@lists.osu.edu"}]
dynamic = ["version", "description"]
